package com.cafeform.dndtools.mbean;

import com.cafeform.dndtools.entity.AlignmentMaster;
import com.cafeform.dndtools.entity.CampaignMaster;
import com.cafeform.dndtools.entity.CharacterAbilityRecord;
import com.cafeform.dndtools.entity.CharacterArmRecord;
import com.cafeform.dndtools.entity.CharacterEquipment;
import com.cafeform.dndtools.entity.CharacterGrowthRecord;
import com.cafeform.dndtools.entity.CharacterRecord;
import com.cafeform.dndtools.entity.CharacterSaveRecord;
import com.cafeform.dndtools.entity.CharacterSkillGrowthRecord;
import com.cafeform.dndtools.entity.CharacterSkillRecord;
import com.cafeform.dndtools.entity.GenderMaster;
import com.cafeform.dndtools.entity.PlayerMaster;
import com.cafeform.dndtools.entity.RaceMaster;
import com.cafeform.dndtools.entity.ReligionMaster;
import com.cafeform.dndtools.entity.SaveMaster;
import com.cafeform.dndtools.entity.SkillMaster;
import java.util.Date;
import java.util.List;
import javax.faces.event.ValueChangeEvent;

public interface CreatureData 
{
    public AlignmentMaster getAlignmentId() ;
    public CampaignMaster getCampaignId() ;
    public CharacterEquipment getCharacterEquipment() ;
    public CharacterRecord getCharacterRecord();;
    public GenderMaster getGenderId() ;
    public Integer geHitPoint();;
    public Integer getAbilityBaseById(int id);;
    public Integer getAbilityFeatModifierById(int id);;
    public Integer getAbilityLevelModifierById(int id);;
    public Integer getAbilityMiscModifierById(int id);;
    public Integer getAbilityModifierById(int ability);;
    public Integer getAbilityRaceModifierById(int id);;
    public Integer getAbilityTotalById(int id);;
    public Integer getAcAbilityModifier() ;
    public Integer getAcArmor() ;
    public Integer getAcFlatFooted() ;
    public Integer getAcMiscMod() ;
    public Integer getAcNormal() ;
    public Integer getAcRaceModifier() ;
    public Integer getAcShield() ;
    public Integer getAcTouch() ;
    public Integer getAge() ;
    public Integer getAttackBonusDexBonus() ;
    public Integer getAttackBonusStrengthBonus() ;
    public Integer getBaseAttackTotal() ;
    public Integer getCharacterLevel() ;
    public Integer getDamageReduction() ;
    public Integer getExpForNextLevel() ;
    public Integer getExperience() ;
    public Integer getGrappleBonus() ;
    public Integer getHeight() ;
    public Integer getHitPoint() ;
    public Integer getId() ;
    public Integer getInitiativeAbilityModifier() ;
    public Integer getInitiativeMiscModifier() ;
    public Integer getInitiativeTotal() ;
    public Integer getMeleeAttackBonus() ;
    public Integer getRangeAttackBonus() ;
    public Integer getSaveAbilityModifierById(int saveId) ;
    public Integer getSaveClassBonusById(int saveId) ;
    public Integer getSaveMiscModifierById(int saveId) ;
    public Integer getSaveRaceModifierById(int saveId) ;
    public Integer getSaveTotalById(int saveId) ;
    public Integer getSheetId() ;
    public Integer getSkillAbilityModifierById(int skill); ;
    public Integer getSkillArmorModifierById(int skillId) ;
    public Integer getSkillMiscModifierById(int index);;
    public Integer getSkillSynergyModifierById(int skillId) ;
    public Integer getSkillTotalCheckModifierById(Integer index);;
    public Integer getSkillTotalCheckModifierById(int id) ;
    public Integer getSkillTotalPointById(int skill);;
    public Integer getSkillTotalRankById(int skillId);;
    public Integer getSpeedFeatModifier() ;
    public Integer getSpeedMiscModifier() ;
    public Integer getSpeedRaceBasse() ;
    public Integer getSpeedTotal() ;
    public Integer getSpellResistance() ;
    public Integer getWeight() ;
    public Integer getskillArmorModifierById(int skillId) ;
    public Integer getskillMiscModifierById(int id) ;
    public Integer getskillSynergyModifierById(int skillId) ;
    public PlayerMaster getPlayerId ();
    public RaceMaster getRaceId() ;
    public ReligionMaster getReligionId() ;
    public SaveMaster getSaveMasterById(int saveId) ;
    public SkillMaster getSkillMasterById(int id) ;
    public String getAttackDescription() ;
    public String getCharacterName() ;
    public String getDefenceDescription() ;
    public String getDescription() ;
    public String getEyeColor() ;
    public String getFeatDescription() ;
    public String getHairColor() ;
    public String getItemDescription() ;
    public String getLanguage() ;
    public String getLastChange() ;
    public String getSkillAbilityNameById(int skill);;
    public String getSkillAbilityShortNameById(int skill);;
    public String getSkinColor() ;
    public String getSpeed() ;
    public String getSpellDescription() ;
    public String getUpdateDescription() ;
    public String getskillAbilityNameById(int id) ;
    public String getskillAbilityShortNameById(int id) ;
    public boolean isSecret ();
    public boolean isSkillAcceptNoRankBySkillId(int skillId);;
    public int getBaseAttackModifier();
    public void setAbilityBaseById(int id, Integer newVal);;
    public void setAbilityFeatModifierById(int id, Integer newVal);;
    public void setAbilityMiscModifierById(int id, Integer newVal);;
    public void setAcArmor(Integer acArmor) ;
    public void setAcMiscMod(Integer acMiscMod) ;
    public void setAcShield(Integer acShield) ;
    public void setAge(Integer age) ;
    public void setAlignmentId(AlignmentMaster alignmentId) ;
    public void setAttackDescription(String attackDescription) ;
    public void setBaseAttackModifier(int modifier);
    public void setCampaignId(CampaignMaster campaignId) ;
    public void setCharacterEquipment(CharacterEquipment characterEquipment) ;
    public void setCharacterName(String characterName) ;
    public void setDamageReduction(Integer damageReduction) ;
    public void setDefenceDescription(String defenceDescription) ;
    public void setDescription(String description) ;
    public void setExperience(Integer experience) ;
    public void setEyeColor(String eyeColor) ;
    public void setFeatDescription(String featDescription) ;
    public void setGenderId(GenderMaster genderId) ;
    public void setHairColor(String hairColor) ;
    public void setHeight(Integer height) ;
    public void setId(Integer id) ;
    public void setInitiativeMiscModifier(Integer modifier) ;
    public void setItemDescription(String itemDescription) ;
    public void setLanguage(String language) ;
    public void setPlayerId (PlayerMaster player);
    public void setRaceId(RaceMaster raceId) ;
    public void setReligionId(ReligionMaster religionId) ;
    public void setSecret (boolean secret);
    public void setSheetId(Integer sheetId) ;
    public void setSkillMiscModifierById(int index, Integer skillMiscModifier);;
    public void setSkinColor(String skinColor) ;
    public void setSpeed(Integer speed) ;
    public void setSpeedFeatModifier(Integer speedFeatModifier) ;
    public void setSpeedMiscModifier(Integer speedMiscModifier) ;
    public void setSpellDescription(String spellDescription) ;
    public void setSpellResistance(Integer spellResistance) ;
    public void setUpdateDescription(String updateDescription) ;
    public void setWeight(Integer weight) ;
    public void textField13_processValueChange(ValueChangeEvent vce) ;
    public void updateGrowthRecord();;
    public String getAttackModifiers (CharacterArmRecord armRecord);
    public List<CharacterSkillRecord> getCharacterSkillRecordList();
    public List<CharacterSkillGrowthRecord> getCharacterSkillGrowthRecordList();
    public List<CharacterGrowthRecord> getCharacterGrowthRecordList();
    public List<CharacterAbilityRecord> getCharacterAbilityRecordList();
    public List<CharacterSaveRecord> getCharacterSaveRecordList();
    public boolean hasSkillRankBySkill(SkillMaster skill);
    public Integer getInitiativeFeatModifier();
    public void setInitiativeFeatModifier(Integer modifier);
    public Date getSaveTime();
    public void setSaveTime(Date saveTime);
    public Float getSkillRankByLevelAndSkill(CharacterGrowthRecord growth, SkillMaster skill);
    public boolean isClassSkillByLevelAndSkill(CharacterGrowthRecord growthLevel, SkillMaster skill);
    public Integer getHitPointAbilityModifier();
    public String getClassList();
}
